## ДЗ 1.  Алгоритм линейной регрессии. Градиентный спуск

1. Подберите скорость обучения (alpha) и количество итераций:

In [108]:
import numpy as np
import matplotlib.pyplot as plt

In [109]:
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [110]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])
X.shape

(2, 10)

In [111]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [112]:
n = X.shape[1]
alpha = 0.01
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [113]:
X, W

(array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 1,  1,  2,  1,  3,  0,  5, 10,  1,  2]]), array([1. , 0.5]))

In [114]:
np.dot(W, X)

array([1.5, 1.5, 2. , 1.5, 2.5, 1. , 3.5, 6. , 1.5, 2. ])

In [76]:
for i in range(600):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
        if i % 100 == 0:
            print(i, W, err)

0 [2.102 0.5  ] 3173.15
0 [2.102 3.9  ] 3173.15
100 [31.88770806  6.77395294] 175.19445858001853
100 [31.88770806  6.74418155] 175.19445858001853
200 [41.83683774  4.91746666] 61.9177717428135
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26470166] 47.913169919666785
300 [45.33508261  4.26102097] 47.913169919666785
400 [46.56511152  4.0351809 ] 46.181755648107604
400 [46.56511152  4.03388672] 46.181755648107604
500 [46.99760587  3.95447839] 45.96769776787538
500 [46.99760587  3.95402334] 45.96769776787538


2 (опция). В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:

In [115]:
for i in range(1000):
    y_pred = np.dot(W, X)
    err = calc_mse(y, y_pred)
    '''for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
    W -= alpha * (1/n * 2 * np.dot(X,(y_pred - y)))
    if i % 100 == 0:
        print(i, W, err)
# поменяли сумму компонентов векторов на скалярное произведение

0 [2.102 3.9  ] 3173.15
100 [31.88770806  6.74418155] 175.19445858001842
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26102097] 47.913169919666785
400 [46.56511152  4.03388672] 46.181755648107604
500 [46.99760587  3.95402334] 45.96769776787538
600 [47.14967657  3.92594232] 45.941233404700036
700 [47.20314662  3.91606866] 45.93796156758051
800 [47.2219474   3.91259695] 45.93755706443538
900 [47.228558    3.91137626] 45.937507054979434


3 (опция). Реализовать один из критериев останова, перечисленный в методичке.